### ISSUE TITLE
Организация кода

### ISSUE THREAD

**Issue by marcha-ua** [BangWooJord/qt_file_processing#1]
Не принято весь код размещать в main.cpp.

**Comment by jaminous** [comment]
Да, сейчас исправлю

**Comment by jaminous** [comment]
> Не принято весь код размещать в main.cpp.

Исправлено.

**Comment by marcha-ua** [comment]
` fileObject **files;` - такого не должно быть. И непонятно зачем переусложнать код.
Мы говорили необходимо исползовать с++17 - где это? почему не используется std::filesystem?

**Comment by jaminous** [comment]
> ` fileObject **files;` - такого не должно быть. И непонятно зачем переусложнать код.
> Мы говорили необходимо исползовать с++17 - где это? почему не используется std::filesystem?

Исправлено
