### ISSUE TITLE
Нужно ли добавлять файл с юнит-тестами к главному проекту в цели?

### ISSUE THREAD

**Issue by jaminous** [BangWooJord/qt_file_processing#2]
Сейчас у меня юнит-тесты - отдельный проект. 
Нужно ли добавить файл с тестами в проект (через config файл cmakelists.txt)?

**Comment by marcha-ua** [comment]
Необходимо проект перенести в Visual Studio 2019.

**Comment by jaminous** [comment]
> Необходимо проект перенести в Visual Studio 2019.

Перенес, создал под проект отдельную ветвь
