### ISSUE TITLE
Организация проекта

### ISSUE THREAD

**Issue by marcha-ua** [BangWooJord/qt_file_processing#3]
_Необходимо проект перенести в Visual Studio 2019._

Где это?
Почему  придыдущая таска закрыта но в мастере изменений нет?

`
extern std::condition_variable buffer_cv;
extern std::mutex buffer_mtx;
extern std::queue<long double> buffer_q;
`

Использование extern  это плохая практика - мы это не допускаем.

https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines

Просьба  прочитать и исправить свой код согласно рекомендациям.

**Comment by jaminous** [comment]
А, ну я просто отдельную ветку создал, хорошо, перенесу в мастер.
С екстерном тоже разберусь

**Comment by jaminous** [comment]
Глобальные переменные переделал в локальные и передаю их по ссылке
